### ISSUE TITLE
Allow entry matching to be done by entry UID

### ISSUE THREAD

**Issue by nblyumberg** [VictorGrycuk/StreamDeck-KeePass#11]
I attempted to use the entry UID to locate my KeePass entries but it did not appear to work. Can the plugin search for the entries using UID? 

Also, if possible can the passphrase for the DB be optional and just leverage the locked/unlocked status?

**Comment by VictorGrycuk** [comment]
Hi @nblyumberg.
I created a [pre-release build](https://github.com/VictorGrycuk/StreamDeck-KeePass/releases/tag/1.5.0-Beta.2) that will allow using the UUID to find the entry. Keep in mind that it will only use the hex string of the UUID, not the base 64 string. Please let me know if it works for you, and I will merge it to master.

Regarding your second question, you want the password to open the DB to be optional? AFAIK, KeePass does not allow a DB with no master password. If you want to retrieve a password while KeePass is unlocked, check the `-auto-type-password` or `-auto-type-password` of the command line version, it might be what you are looking for.

**Comment by nblyumberg** [comment]
Thank you for a super quick turnaround on this! I tested it but it doesn't appear to be working. 
I created two identical shortcuts on the StreamDeck but referenced one field by the name "example" and that worked fine, however trying to use the UUID in hex format, it gives the exclamation mark on execution. I am only using the left side of the UUID without the comma.

![image](https://user-images.githubusercontent.com/17443495/148864165-6bccd926-eb6f-4339-a0f1-ae09d59fcea5.png)

I am aware of the command line parameter option, but I was never able to get it to work correctly using this as my execution string:
"C:\Program Files\KeePass\KeePass.exe" -uuid:7B02773A041C8040BE91CE10485A0F2B -auto-type-password 

I've also tried with the auto-type-password in the middle between the path and the uuid argument. Also, there's probably a difference, albeit a minor one with the auto type just typing the string, while your plugin is putting the password into the clipboard.

**Comment by VictorGrycuk** [comment]
Thank you for the quick response, @nblyumberg.
That is weird, it worked with all my personal entries. I changed the code to validate that if the title doesn't match, then it will try to [match the UUID](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/dev/search-by-uuid/StreamDeck-KeePass/StreamDeck-KeePass/KeePassRetrieve.cs#L104).
Just to be sure, the name of the field on Stream Deck was updated to _Entry Name **or UUID**_, right?

Regarding the `-auto-type-password`, sorry to hear it doesn't work. I haven't used it myself, but I hoped that it would be a workaround.

The thing is, going back to the original question, that the DB and KeePass are two different entities. This plugin uses the KeePass Lib to connect directly to the DB, but it's not aware if the DB is open/unlocked in the KeePass application.

The only way I see it working is with a plug in on the KeePass app, so that this plug in communicates with the KeePass app to retrieve info instead of the DB itself. But that is actually outside of my knowledge.

**Comment by nblyumberg** [comment]
yes, I uninstalled the plugin from Stream Deck and then double clicked the downloaded file which prompted for it to be installed. The field caption did update to reflect Entry Name or UUID. I then made 2 of the same entries on the Stream Deck

![image](https://user-images.githubusercontent.com/17443495/149017366-20367743-9786-44b1-a385-d2e158039c07.png)
vs
![image](https://user-images.githubusercontent.com/17443495/149017505-6c2a423f-cdf0-4627-8a8b-ff06660cd964.png)

The "example" name reference works, but the UUID version does not. The reason for the UUID request is that "name" of a record is not unique, you can have multiple records in the database referencing the same thing, but UUID would be unique.

---
With regards to the password question I asked, it's a security consideration. Where do you store the password to the database? is it plaintext? How easy is it for someone to figure that out and get your master password along with all the passwords in the KeePass DB? I've used AutoHotKey quite often with KeePass to launch SSH sessions using the open command line parameter when the DB is unlocked. I was hoping there was a way for you to do something similar for password retrieval when the database is unlocked thus allowing the password not to be resident somewhere on the system.

**Comment by nblyumberg** [comment]
Oops, I realized that my screenshot has the base64 encoded UUID, but I tested it with both (just don't want to give you the wrong impression)

**Comment by VictorGrycuk** [comment]
I agree with you that it should have been the UUID from the start rather the entry title, but for whatever reason I went with the title. To keep retro compatibility with previous versions of the plug in, I will keep the title validation. However, I will need to check first for the UUID and then for the title (unlike beta release I drafted).

In any case, I will keep doing tests. I will try to reproduce the issue you are having.

Regarding the security concerns, those are completely valid concerns.
None of the information is being stored to files. The configuration is [simply an HTML](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/master/StreamDeck-KeePass/StreamDeck-KeePass/PropertyInspector/KeePassRetrievePI.html#L22-L25) called [Property Inspector](https://developer.elgato.com/documentation/stream-deck/sdk/property-inspector/), that information is then parsed by the SDK I used ([StreamDeck Tools](https://github.com/BarRaider/streamdeck-tools)), which returns the information as a [configuration class](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/master/StreamDeck-KeePass/StreamDeck-KeePass/KeePassRetrieve.cs#L16-L46), that I then use to [open the DB](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/master/StreamDeck-KeePass/StreamDeck-KeePass/KeePassRetrieve.cs#L76-L80) using the KeePass Lib.
The code could use several improvements, and I am open to suggestions.

As far as I know, the password only stays in memory for the life of the plugin. But since the property inspector is an HTML, someone with access to your computer could modify the property inspector to show the password as plain text.

This is a wild idea and I will have to test it to see if it will work, but I can try to make a third action that instead of using the KeePass Lib, it would call the KeePass.exe with parameters to retrieve the passwords, as in emulating the command line calls.

**Comment by VictorGrycuk** [comment]
@nblyumberg I got some updates regarding trying to retrieve passwords without having to use passwords.
I thought it was possible to use parameters for KeePass to retrieve entries, but I found it is [limited on its capabilities](https://keepass.info/help/base/cmdline.html). However, I found a plugin called [KeePassCommander](https://keepass.info/plugins.html#keepasscmdr) that does exactly what we need, allows applications to retrieve info from an already opened DB.

I did a quick and dirty test modifying the existing stream deck plugin, and it worked. I was able to retrieve a sample entry by only adding the path to `KeePassCommandDll.dll` (provided by the plugin). I tried the same with KeePass app closed, but it was not possible to retrieve the entry.

However, the connector [doesn't seem to return the UUID](https://github.com/MircoBabin/KeePassCommander/blob/master/src/KeePassCommandDll/Api.cs#L48-L74), therefore, it might not be able to search an entry by the UUID. I might need to poke around to see if it is possible, but at first sight I don't think it is possible (without modifying the original code).

So, this mean that I could be able to make a third action with at least two parameters, the entry's title and the path to the KeePassCommander's DLL, which would copy the desired value to the clipboard.

Let me know what you think of this alternative.
