### ISSUE TITLE
Keepass db path isn't saved

### ISSUE THREAD

**Issue by Jubess** [VictorGrycuk/StreamDeck-KeePass#13]
When I enter the path for the keepass db it doesn't persist the value. When I enter the data and go to a different button and then back, the KeePass db path is empty. When I enter all the the config and press the button on the streamdeck it logs the following:

2022-01-20 10:27:27.0793|INFO|BarRaider.SdTools.Logger|Value cannot be null.
Parameter name: value

**Comment by VictorGrycuk** [comment]
Hi @Jubess, I believe that is because there must be some other required field that you are not filling, like the password or entry name (or both).

**Comment by Jubess** [comment]
Well I have all the fields filled except key file path because I don't have one. But once I leave the config file and come back to it, then the db path is empty

**Comment by VictorGrycuk** [comment]
In that case, I will do some tests and get back to you when I have an update.

**Comment by Jubess** [comment]
I fixed by filling in some random numbers in the key file path, then it did safe it. But then it gave an error on the key ( logically) so when I removed the key again, it remembered the DB path. A little wonky, but maybe this will help someone else with the same problem

**Comment by VictorGrycuk** [comment]
I found that both the db Password and the key file sections of the PI file for the retrieve action [had the same ID](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/master/StreamDeck-KeePass/StreamDeck-KeePass/PropertyInspector/KeePassRetrievePI.html#L18-L25).
I am not sure if that might have cause the issue, but it will be fixed in the new version anyway.

I will close the issue for the moment, if I see more people reporting this, I will take a closer look.

**Comment by VictorGrycuk** [comment]
I may have found the actual issue behind this.
The [DB Path field didnt have](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/master/StreamDeck-KeePass/StreamDeck-KeePass/PropertyInspector/KeePassRetrievePI.html#L16) the `oninput="setSettings()"`, therefore its content was not being saved until another field did. Major oversight!

This fix will be also included in the next version.
