### ISSUE TITLE
Neither Retrieve or Generate is working

### ISSUE THREAD

**Issue by rtewell** [VictorGrycuk/StreamDeck-KeePass#4]
Hi - Using version 2.46 -- Generate PW and Retrieve are not working, any ideas why?

Configuration here:

https://i.imgur.com/JNWrXmP.png

When button is pressed, the LCD puts a Yellow exclamation mark and does nothing.

Thanks. :)

**Comment by VictorGrycuk** [comment]
@rtewell Thank you for reporting the issue, sorry for the late response.
If a yellow exclamation appears it means one of two:
- The entry is not found on the keepass db
- There is some internal error that makes the app fail

Something that I haven't specified in the readme is that the entry name is [case sensitive](https://github.com/VictorGrycuk/StreamDeck-KeePass/blob/master/StreamDeck-KeePass/StreamDeck-KeePass/KeePassRetrieve.cs#L96), so be sure that the case of the entry in the configuration is the same as in the db.

If you are in Windows, you can go to the folder `%appdata%\Elgato\StreamDeck\Plugins\com.victorgrycuk.keepass.sdPlugin` and you should find a file named `pluginlog.log`. See if in there is anything that might indicate the problem.

About retrieve, since it does not connect to the keepass db, make sure that your configuration is valid.
Again, the logfile might give an indication if an internal error happened.

**Comment by rtewell** [comment]
Thanks for the log. The error provided was

2020-11-04 19:06:36.0567|INFO|BarRaider.SdTools.Logger|Could not find file 'C:\temp\Database.kbdx'.

My assumption is that the plugin and/or streamdeck did not have the ability to jump into that folder. Once I moved the database to the plugin folder it started working as expected.

Does it require at least one database to be connected in order to generate a key?

**Comment by VictorGrycuk** [comment]
Thanks @rtewell.
I just took a closer look at the capture you provided, and noticed that the file extension is `.kbdx` instead of `.kdbx`, that might have been the reason it couldn't file the db file.

Regarding the password generation not working, try deleting the log file, execute the password generation app, and check the log file again. Hopefully it will log any error that might be happening.

The generation of the keys does not require a keepass db, it should use the `KeePassLib.dll` that is stored in the same folder where you found the log file, and both apps should work independently of each other.

I will improve the file path validation and error messages for the next version.

**Comment by rtrada** [comment]
I agree that what I sent makes more sense, that was a personal elgato I was trying to troubleshoot at home and unfortunately fatfingered the path.

However what made me put this ticket in to begin with was the fact it's not working at work, which is where the real value is. This is the log.

2020-11-05 09:09:07.6899|INFO|BarRaider.SdTools.Logger|Destructor called
2020-11-05 09:09:53.7821|INFO|BarRaider.SdTools.Logger|This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

**Comment by rtewell** [comment]
Hey, so after further review it looks like it was because the database is FIPS encrypted that it was not working, and when I went to try it at home I simply had the wrong path. 

No fault of yours, just FIPS crippling functionality as always. 

Thanks for the response.

**Comment by VictorGrycuk** [comment]
Thanks for reporting it, @rtewell!
That is something worth of nothing on the readme in case someone else run into the same issue.

Unless you have any further questions or issues, I will close this issue.

**Comment by rtewell** [comment]
Nope, go ahead. Thanks
